/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prj_nota.Pck_View;
import com.mycompany.prj_nota.Pck_Control.ClienteControl;
import com.mycompany.prj_nota.Pck_Control.PedidoControl;
import com.mycompany.prj_nota.Pck_Control.ItemControl;
import com.mycompany.prj_nota.Pck_Control.ProdutoControl;
import com.mycompany.prj_nota.Pck_Model.ClienteModel;
import com.mycompany.prj_nota.Pck_Model.PedidoModel;
import com.mycompany.prj_nota.Pck_Model.ProdutoModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Aluno
 */
public class NotaView extends javax.swing.JFrame {

    /**
     * Creates new form notaView
     */
    public NotaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notaLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        codigoClienteCombo = new javax.swing.JComboBox<>();
        codigoclienteLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        numeroText = new javax.swing.JTextField();
        cpfText = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        dataText = new javax.swing.JTextField();
        enderecoLabel = new javax.swing.JLabel();
        enderecoText = new javax.swing.JTextField();
        inserirButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        codigoitemLabel = new javax.swing.JLabel();
        codigoitemText = new javax.swing.JTextField();
        codigoprodutoLabel = new javax.swing.JLabel();
        codigoProdutoCombo = new javax.swing.JComboBox<>();
        quantidadeLabel = new javax.swing.JLabel();
        valoritemLabel = new javax.swing.JLabel();
        quantidadeText = new javax.swing.JTextField();
        valoritemText = new javax.swing.JTextField();
        inserirItemButton = new javax.swing.JButton();
        removerItemButton = new javax.swing.JButton();
        alterarItemButton = new javax.swing.JButton();
        consultarItemButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codigoPedidoCombo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        clientesMenu = new javax.swing.JMenu();
        produtoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notaLabel.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        notaLabel.setText("Nota");

        numeroLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numeroLabel.setText("Numero nota:");

        codigoClienteCombo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigoClienteCombo.setDoubleBuffered(true);
        codigoClienteCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoClienteComboMouseClicked(evt);
            }
        });
        codigoClienteCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoClienteComboActionPerformed(evt);
            }
        });

        codigoclienteLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigoclienteLabel.setText("Codigo cliente:");

        cpfLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpfLabel.setText("Cpf:");

        numeroText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numeroText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTextActionPerformed(evt);
            }
        });

        cpfText.setEditable(false);
        cpfText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dataLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataLabel.setText("Data:");

        dataText.setEditable(false);
        dataText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        enderecoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enderecoLabel.setText("Endereço");

        enderecoText.setEditable(false);
        enderecoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        inserirButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inserirButton.setText("inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirButtonActionPerformed(evt);
            }
        });

        removerButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removerButton.setText("remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        alterarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alterarButton.setText("alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        consultarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarButton.setText("consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        codigoitemLabel.setText("Codigo item:");

        codigoitemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoitemTextActionPerformed(evt);
            }
        });

        codigoprodutoLabel.setText("Codigo Produto:");

        codigoProdutoCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoProdutoComboMouseClicked(evt);
            }
        });
        codigoProdutoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProdutoComboActionPerformed(evt);
            }
        });

        quantidadeLabel.setText("Quantidade:");

        valoritemLabel.setText("Valor item:");

        inserirItemButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inserirItemButton.setText("inserir");
        inserirItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirItemButtonActionPerformed(evt);
            }
        });

        removerItemButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removerItemButton.setText("remover");
        removerItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemButtonActionPerformed(evt);
            }
        });

        alterarItemButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alterarItemButton.setText("alterar");
        alterarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarItemButtonActionPerformed(evt);
            }
        });

        consultarItemButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarItemButton.setText("consultar");
        consultarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarItemButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Pedido");

        codigoPedidoCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoPedidoComboMouseClicked(evt);
            }
        });
        codigoPedidoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPedidoComboActionPerformed(evt);
            }
        });

        clientesMenu.setText("Clientes");
        clientesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(clientesMenu);

        produtoMenu.setText("Produtos");
        produtoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(produtoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantidadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoitemLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoitemText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(codigoprodutoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoProdutoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoPedidoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valoritemLabel)
                                .addGap(21, 21, 21)
                                .addComponent(valoritemText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dataLabel)
                                            .addComponent(notaLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dataText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(cpfLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codigoclienteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codigoClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enderecoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(inserirButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removerButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alterarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(consultarButton)))
                                .addGap(54, 54, 54)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inserirItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarItemButton)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(notaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoclienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel)
                    .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(consultarButton)
                    .addComponent(alterarButton)
                    .addComponent(removerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoitemLabel)
                    .addComponent(codigoitemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoprodutoLabel)
                    .addComponent(codigoProdutoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(codigoPedidoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeLabel)
                    .addComponent(valoritemLabel)
                    .addComponent(quantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valoritemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirItemButton)
                    .addComponent(consultarItemButton)
                    .addComponent(alterarItemButton)
                    .addComponent(removerItemButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTextActionPerformed

    private void inserirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirButtonActionPerformed
        // TODO add your handling code here:
        //numeroText.getText();
        //codigoClientCombo.getText();
        //dataText.getText();
        //nomeCombo.getText();
        //cpfText.getText();
        //enderecoText.getText();
        PedidoControl pc = new PedidoControl();
        String clienteSelecionado = codigoClienteCombo.getSelectedItem().toString();
        try{
            Date dataPedido = new Date();
            pc.inserirPedido(dataPedido, 0, Integer.parseInt(clienteSelecionado));

        }catch(NumberFormatException e){
            System.out.println(e.toString());
        }        
    }//GEN-LAST:event_inserirButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        // TODO add your handling code here:
        PedidoControl pc = new PedidoControl();
        pc.removerPedido(Integer.parseInt(numeroText.getText()));
    }//GEN-LAST:event_removerButtonActionPerformed

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        // TODO add your handling code here:
        PedidoControl pc = new PedidoControl();
        pc.consultarPedido(Integer.parseInt(numeroText.getText()));
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void inserirItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirItemButtonActionPerformed
        // TODO add your handling code here:
        ItemControl ic = new ItemControl();
        String produtoSelecionado = codigoProdutoCombo.getSelectedItem().toString();
        ic.inserirItem(Integer.parseInt(produtoSelecionado),
                        Integer.parseInt(codigoPedidoCombo.getSelectedItem().toString()),
                        Integer.parseInt(quantidadeText.getText()),
                        Integer.parseInt(valoritemText.getText()));
        
    }//GEN-LAST:event_inserirItemButtonActionPerformed

    private void removerItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemButtonActionPerformed
        // TODO add your handling code here:
        ItemControl ic = new ItemControl();
        ic.deletarItem(Integer.parseInt(codigoitemText.getText()));
    }//GEN-LAST:event_removerItemButtonActionPerformed

    private void consultarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarItemButtonActionPerformed
        // TODO add your handling code here:
        ItemControl ic = new ItemControl();
        ic.consultarItem(Integer.parseInt(codigoitemText.getText()));
    }//GEN-LAST:event_consultarItemButtonActionPerformed

    private void codigoitemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoitemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoitemTextActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        // TODO add your handling code here:
        PedidoControl pc = new PedidoControl();
        String clienteSelecionado = codigoClienteCombo.getSelectedItem().toString();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try{
            Date dataPedido = format.parse(dataText.getText());
            pc.atualizarPedido(Integer.parseInt(numeroText.getText()),dataPedido ,Double.parseDouble(valoritemText.getText()), Integer.parseInt(clienteSelecionado));


        }catch(Exception ex){
        }  
    }//GEN-LAST:event_alterarButtonActionPerformed

    private void alterarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarItemButtonActionPerformed
        // TODO add your handling code here:
        ItemControl ic = new ItemControl();
        String produtoSelecionado = codigoProdutoCombo.getSelectedItem().toString();
        ic.atualizarItem(Integer.parseInt(codigoitemText.getText()),Integer.parseInt(produtoSelecionado),
                        Integer.parseInt(numeroText.getText()),
                        Integer.parseInt(quantidadeText.getText()),
                        Integer.parseInt(valoritemText.getText()));
    }//GEN-LAST:event_alterarItemButtonActionPerformed

    private void clientesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMenuMouseClicked
        // TODO add your handling code here:
        ClienteView cv = new ClienteView();
        cv.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesMenuMouseClicked

    private void produtoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoMenuMouseClicked
        // TODO add your handling code here:
        ProdutoView pv = new ProdutoView();
        pv.setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoMenuMouseClicked

    private void codigoClienteComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoClienteComboMouseClicked
        // TODO add your handling code here:
        ClienteControl cc = new ClienteControl();
        List<ClienteModel> clientes = cc.consultarClientes();
        codigoClienteCombo.removeAllItems();
        for(ClienteModel c : clientes ){
            codigoClienteCombo.addItem(String.valueOf(c.getA01_codigo()));
        }
    }//GEN-LAST:event_codigoClienteComboMouseClicked

    private void codigoProdutoComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoProdutoComboMouseClicked
        // TODO add your handling code here:
        ProdutoControl pc = new ProdutoControl();
        List<ProdutoModel> produtos = pc.consultarProdutos();
        if(produtos.isEmpty()){
            codigoProdutoCombo.addItem("0");
        }
        for(ProdutoModel p : produtos){
            codigoProdutoCombo.addItem(String.valueOf(p.getA03_codigo()));
        }
    }//GEN-LAST:event_codigoProdutoComboMouseClicked

    private void codigoClienteComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoClienteComboActionPerformed
        // TODO add your handling code here:
       String clienteSelecionado = (String) codigoClienteCombo.getSelectedItem();
    
    try {
        Integer codigoClienteSelecionado = Integer.parseInt(clienteSelecionado);
        
        ClienteControl cc = new ClienteControl();
        ClienteModel cliente = cc.consultarCliente(codigoClienteSelecionado);
        
        cpfText.setText(cliente.getA01_cpf());
        enderecoText.setText(cliente.getA01_endereco());
        
        Date dataAtual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        dataText.setText(formato.format(dataAtual));
        
    } catch (NumberFormatException e) {
        System.err.println("Erro ao converter o código do cliente: " + e.getMessage());
    }
    }//GEN-LAST:event_codigoClienteComboActionPerformed

    private void codigoPedidoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPedidoComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_codigoPedidoComboActionPerformed

    private void codigoPedidoComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoPedidoComboMouseClicked
        // TODO add your handling code here:
        codigoPedidoCombo.removeAllItems();
        PedidoControl pc = new PedidoControl();
        List<PedidoModel> pedidos = pc.consultarPedidos();
        for(PedidoModel p : pedidos){
            codigoPedidoCombo.addItem(String.valueOf(p.getA02_codigo()));
        }
    }//GEN-LAST:event_codigoPedidoComboMouseClicked

    private void codigoProdutoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProdutoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new com.mycompany.prj_nota.Pck_View.NotaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JButton alterarItemButton;
    private javax.swing.JMenu clientesMenu;
    private javax.swing.JComboBox<String> codigoClienteCombo;
    private javax.swing.JComboBox<String> codigoPedidoCombo;
    private javax.swing.JComboBox<String> codigoProdutoCombo;
    private javax.swing.JLabel codigoclienteLabel;
    private javax.swing.JLabel codigoitemLabel;
    private javax.swing.JTextField codigoitemText;
    private javax.swing.JLabel codigoprodutoLabel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton consultarItemButton;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfText;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField dataText;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoText;
    private javax.swing.JButton inserirButton;
    private javax.swing.JButton inserirItemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel notaLabel;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroText;
    private javax.swing.JMenu produtoMenu;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JTextField quantidadeText;
    private javax.swing.JButton removerButton;
    private javax.swing.JButton removerItemButton;
    private javax.swing.JLabel valoritemLabel;
    private javax.swing.JTextField valoritemText;
    // End of variables declaration//GEN-END:variables
}
