/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prj_nota.Pck_View;
import com.mycompany.prj_nota.Pck_Control.PedidoControl;
import java.text.SimpleDateFormat;

/**
 *
 * @author Aluno
 */
public class NotaView extends javax.swing.JFrame {

    /**
     * Creates new form notaView
     */
    public NotaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notaLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        codigoclienteCombo = new javax.swing.JComboBox<>();
        codigoclienteLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        numeroText = new javax.swing.JTextField();
        cpfText = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        dataText = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        nomeCombo = new javax.swing.JComboBox<>();
        enderecoLabel = new javax.swing.JLabel();
        enderecoText = new javax.swing.JTextField();
        inserirButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        codigoitemLabel = new javax.swing.JLabel();
        codigoitemText = new javax.swing.JTextField();
        codigoprodutoLabel = new javax.swing.JLabel();
        codigoprodutoCombo = new javax.swing.JComboBox<>();
        nomeprodutoText = new javax.swing.JTextField();
        nomeprodutoLabel = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JLabel();
        valorunitarioLabel = new javax.swing.JLabel();
        valoritemLabel = new javax.swing.JLabel();
        quantidadeText = new javax.swing.JTextField();
        valorunitarioText = new javax.swing.JTextField();
        valoritemText = new javax.swing.JTextField();
        inserirProdutoButton = new javax.swing.JButton();
        removerProdutoButton = new javax.swing.JButton();
        alterarProdutoButton = new javax.swing.JButton();
        consultarProdutoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notaLabel.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        notaLabel.setText("Nota");

        numeroLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numeroLabel.setText("Numero nota:");

        codigoclienteCombo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigoclienteCombo.setDoubleBuffered(true);

        codigoclienteLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigoclienteLabel.setText("Codigo cliente:");

        cpfLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpfLabel.setText("Cpf:");

        numeroText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numeroText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTextActionPerformed(evt);
            }
        });

        cpfText.setEditable(false);
        cpfText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dataLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataLabel.setText("Data:");

        dataText.setEditable(false);
        dataText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        nomeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeLabel.setText("Nome:");

        nomeCombo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        enderecoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enderecoLabel.setText("Endereço");

        enderecoText.setEditable(false);
        enderecoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        inserirButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inserirButton.setText("inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirButtonActionPerformed(evt);
            }
        });

        removerButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removerButton.setText("remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        alterarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alterarButton.setText("alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        consultarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarButton.setText("consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        codigoitemLabel.setText("Codigo item:");

        codigoitemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoitemTextActionPerformed(evt);
            }
        });

        codigoprodutoLabel.setText("Codigo Produto:");

        nomeprodutoLabel.setText("Nome produto:");

        quantidadeLabel.setText("Quantidade:");

        valorunitarioLabel.setText("Valor unitario:");

        valoritemLabel.setText("Valor item:");

        inserirProdutoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inserirProdutoButton.setText("inserir");
        inserirProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirProdutoButtonActionPerformed(evt);
            }
        });

        removerProdutoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removerProdutoButton.setText("remover");
        removerProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProdutoButtonActionPerformed(evt);
            }
        });

        alterarProdutoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alterarProdutoButton.setText("alterar");

        consultarProdutoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarProdutoButton.setText("consultar");
        consultarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProdutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(numeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(codigoclienteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codigoclienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cpfLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpfText)))
                                .addGap(38, 38, 38)
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dataLabel)
                                    .addComponent(notaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(inserirButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(removerButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(alterarButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(consultarButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(enderecoLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inserirProdutoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerProdutoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterarProdutoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(consultarProdutoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoitemLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoitemText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoprodutoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoprodutoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeprodutoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeprodutoText, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(quantidadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorunitarioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorunitarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valoritemLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valoritemText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(notaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoclienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoclienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel)
                    .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(consultarButton)
                    .addComponent(alterarButton)
                    .addComponent(removerButton))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoitemLabel)
                    .addComponent(codigoitemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoprodutoLabel)
                    .addComponent(codigoprodutoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeprodutoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeprodutoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeLabel)
                    .addComponent(valorunitarioLabel)
                    .addComponent(valoritemLabel)
                    .addComponent(quantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorunitarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valoritemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirProdutoButton)
                    .addComponent(consultarProdutoButton)
                    .addComponent(alterarProdutoButton)
                    .addComponent(removerProdutoButton))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTextActionPerformed

    private void inserirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirButtonActionPerformed
        // TODO add your handling code here:
        //numeroText.getText();
        //codigoClientCombo.getText();
        //dataText.getText();
        //nomeCombo.getText();
        //cpfText.getText();
        //enderecoText.getText();
        PedidoControl pc = new PedidoControl();
        String clienteSelecionado = codigoclienteCombo.getSelectedItem().toString();
        SimpleDateFormat dataPedido = new SimpleDateFormat("dd/MM/yyyy");
        pc.inserirPedido(dataPedido.parse(dataText.getText()), Double.parseDouble(valoritemText.getText()), Integer.parseInt(clienteSelecionado));
        
    }//GEN-LAST:event_inserirButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        // TODO add your handling code here:
        PedidoControl pc = new PedidoControl();
        pc.excluirPedido(Integer.parseInt(numeroText.getText()));
    }//GEN-LAST:event_removerButtonActionPerformed

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        // TODO add your handling code here:
        PedidoControl pc = new PedidoControl();
        pc.consultarPedido(Integer.parseInt(numeroText.getText()));
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void inserirProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirProdutoButtonActionPerformed

    private void removerProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerProdutoButtonActionPerformed

    private void consultarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarProdutoButtonActionPerformed

    private void codigoitemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoitemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoitemTextActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        // TODO add your handling code here:
        PedidoControl pc = new PedidoControl();
        String clienteSelecionado = codigoclienteCombo.getSelectedItem().toString();
        SimpleDateFormat dataPedido = new SimpleDateFormat("dd/MM/yyyy");
        pc.atualizarPedido(Integer.parseInt(numeroText.getText()),dataPedido.parse(dataText.getText()), Double.parseDouble(valoritemText.getText()), Integer.parseInt(clienteSelecionado));
    }//GEN-LAST:event_alterarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(com.mycompany.prj_nota.Pck_View.NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new com.mycompany.prj_nota.Pck_View.NotaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JButton alterarProdutoButton;
    private javax.swing.JComboBox<String> codigoclienteCombo;
    private javax.swing.JLabel codigoclienteLabel;
    private javax.swing.JLabel codigoitemLabel;
    private javax.swing.JTextField codigoitemText;
    private javax.swing.JComboBox<String> codigoprodutoCombo;
    private javax.swing.JLabel codigoprodutoLabel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton consultarProdutoButton;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfText;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField dataText;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoText;
    private javax.swing.JButton inserirButton;
    private javax.swing.JButton inserirProdutoButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> nomeCombo;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomeprodutoLabel;
    private javax.swing.JTextField nomeprodutoText;
    private javax.swing.JLabel notaLabel;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroText;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JTextField quantidadeText;
    private javax.swing.JButton removerButton;
    private javax.swing.JButton removerProdutoButton;
    private javax.swing.JLabel valoritemLabel;
    private javax.swing.JTextField valoritemText;
    private javax.swing.JLabel valorunitarioLabel;
    private javax.swing.JTextField valorunitarioText;
    // End of variables declaration//GEN-END:variables
}
